#!/usr/bin/env python

# NOTE: this is just a mock for reboot effect, to simulate and research remotely

import os
import time
import sys

unbuffered = os.fdopen(sys.stdout.fileno(), 'w', 0)
sys.stdout = unbuffered

def xprint(message, end='\n'):
    unbuffered.write(message + end)

xprint('Are you sure to reboot now ? (y/n) ', end='')
try:
    c = raw_input()
except EOFError:
    c = ''

if c.strip().lower() in ['y', 'yes']:
    xprint('System reboot now...')
    time.sleep(2)
    xprint('Reboot completed')

unbuffered.close()
